version: '2'
services:

  golang-app:
    build: golang
    container_name: golang
    depends_on:
    - rabbitmq
    ports:
    - 8080:80
#    command: go run web-app.go

  rabbitmq:
    build: rabbitmq
    container_name: go_rabbitmq
    volumes:
    - './rabbitmq/volume:/var/lib/rabbitmq:cached'
    ports:
    - 15672:15672

